/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BreachMonitorRouteImport } from './routes/breach-monitor'
import { Route as ExplainRouteImport } from './routes/explain'
import { Route as ModelStatsRouteImport } from './routes/model-stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BreachMonitorRoute = BreachMonitorRouteImport.update({
  id: '/breach-monitor',
  path: '/breach-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainRoute = ExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelStatsRoute = ModelStatsRouteImport.update({
  id: '/model-stats',
  path: '/model-stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breach-monitor': typeof BreachMonitorRoute
  '/explain': typeof ExplainRoute
  '/model-stats': typeof ModelStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breach-monitor': typeof BreachMonitorRoute
  '/explain': typeof ExplainRoute
  '/model-stats': typeof ModelStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breach-monitor': typeof BreachMonitorRoute
  '/explain': typeof ExplainRoute
  '/model-stats': typeof ModelStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/breach-monitor' | '/explain' | '/model-stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/breach-monitor' | '/explain' | '/model-stats'
  id: '__root__' | '/' | '/breach-monitor' | '/explain' | '/model-stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreachMonitorRoute: typeof BreachMonitorRoute
  ExplainRoute: typeof ExplainRoute
  ModelStatsRoute: typeof ModelStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breach-monitor': {
      id: '/breach-monitor'
      path: '/breach-monitor'
      fullPath: '/breach-monitor'
      preLoaderRoute: typeof BreachMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain': {
      id: '/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof ExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-stats': {
      id: '/model-stats'
      path: '/model-stats'
      fullPath: '/model-stats'
      preLoaderRoute: typeof ModelStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreachMonitorRoute: BreachMonitorRoute,
  ExplainRoute: ExplainRoute,
  ModelStatsRoute: ModelStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
